Lab9
mshnschnko/CompGraphics pull request #9
Opened 2024-04-14 14:26 UTC by mshnschnko

2024-04-15 08:56 UTC, Sairsey requested changes

2024-04-15 08:56 UTC, Sairsey commented on lab/Consts.h
>  #define MAX_CUBES 6
Я вам уже говорил в лабораторной 7 что такое количество кубов слишком мало для того чтобы понять прирост в производительности. Давайте найдем с вами то число кубов, при котором GPU Culling имеет смысл. Для этого 
 1) Добавьте возможность в IMGUI переключать режим отрисовки - (CPU, Instancing, GPU Culling + Instancing). 
 2) Добавьте замер времени - сколько миллисекунд требуется на выполнение Renderer::Render и Renderer::Frame (при помощи std::chrono). 
 3) Запустите с разными параметрами и разным числом кубов например 10, 100, 1000, 10000. Замеры представьте в графиком и пришлите мне его сюда.

2024-04-15 09:19 UTC, Sairsey commented on lab/Consts.h
>  #define MAX_CUBES 6
Я понимаю что задание непростое, поэтому сдвину дедлайн по нему до 19-ого числа

2024-04-15 09:38 UTC, Sairsey commented on lab/Consts.h
>  #define MAX_CUBES 6
Я понимаю что задание непростое, поэтому я попытаюсь сдвинуть дедлайн по нему до 19-ого числа. Но не гарантирую что получится, постарайтесь сделать сегодня.

2024-04-17 21:00 UTC, mshnschnko commented
## Графики производительности в зависимости от количества кубов. 

![frame](https://github.com/mshnschnko/CompGraphics/assets/82474547/e2b4fd2a-42ce-4759-a3be-6c8feb7dc69d)
![render_all](https://github.com/mshnschnko/CompGraphics/assets/82474547/c794661f-bdf7-48d2-9509-74d8714186ee)
![render](https://github.com/mshnschnko/CompGraphics/assets/82474547/990b9d6d-ba5c-476b-a88a-e7a224c93a66)

2024-04-17 21:37 UTC, Sairsey approved these changes
Результаты у вас получились интересные, но в любом случае лабораторная принята.

2024-04-17 21:38 UTC, merged